### ISSUE TITLE
Mainnet checklist

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#101]
Do we know our limitations on the following? Is it documented?
- [ ] Alchemy endpoint rate limitations
- [x] Gas costs
- [x] Collateral estimates
- [x] Exchange api rates?
- [ ] ec2 health monitoring set up?
- [x] all of our current trust assumptions

Are all possible attack vectors known and documented?
- [x] gas costs
- [x] stale collateral
- [x] dispute costs (through fund recovery)

Code Reviews
- [x] contract tests/code final review
- [x] validator/state generator tests/code final review
- [x] do we need ALL those logs tho
- [x] everything is using latest contracts/hub/client versions

Random
- [x] branch cleanup?
- [ ] tagged v1.1.x branch?
- [ ] stable docker version?
