### ISSUE TITLE
[all] Watcher module

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#1039]
This is a tracker issue for the creation of the watcher module, [spec](https://paper.dropbox.com/doc/Dispute-Service-Spec--AyQTQaOwjg6b2orqlEpM4AopAg-Sm1C4TYOPSO92cGGKuipX).

## Relevant issues:
- [ ] create types for initialization, interfaces #1034 
- [ ] implement `ChainListener` class #1035
- [ ] implement `Watcher` contract calls, `disable` / `enable` #1036
- [ ] implement `Watcher` dispute initiation #1037
- [ ] add watcher to node/client #1038
