### ISSUE TITLE
Dashboard Next Steps

### ISSUE THREAD

**Issue by hthillman** [ConnextProject/indra#609]
MVP Dashboard is live, but lots more to do:

- [x] Refactor to use styled components instead of stylesheets
- [x] Add token auth
- [ ] Refactor endpoints to use CF functions instead of hitting db directly (future-proofing)
- [x] Add transfer filtering by date
- [ ] chart transfer volume over time **[IN PROGRESS]**
- [ ] chart value locked over time **[IN PROGRESS]**
- [x] Add data export (transfers & channels)
    - [x] add time filter for data export
- [x] "Quick look" stats for channels **[IN PROGRESS]**
    - [ ] # of running app instances
    - [ ] how many proposed apps
    - [x] free balance
    - [x] how many transfers can be reclaimed

**Comment by LayneHaber** [comment]
> Easily identify channels with running app instances

what exactly does this mean?

> Refactor to use CF functions instead of hitting hub

you'll need to create a node with access to the store, im not sure exactly how you'd do this very easily. maybe im misunderstanding?

one thing that would be nice is a quick look stats section when you select a channel. things like:
- how many proposed apps does this channel have?
- how many of the transfer apps can be reclaimed for this channel
etc.

**Comment by hthillman** [comment]
1 - I was thinking it would be helpful to be able to flag channels where an app instance hasn't uninstalled correctly

2 - That's my understanding. I haven't looked into it much yet, but Rahul recommended this as a better way to get free balance vs. slamming nats with requests cc @rhlsthrm 

3- love it

**Comment by rhlsthrm** [comment]
> 2 - That's my understanding. I haven't looked into it much yet, but Rahul recommended this as a better way to get free balance vs. slamming nats with requests cc @rhlsthrm

Well, what I was saying was within the hub use the CF node functions rather than direct DB queries. This way we are using the node abstraction as the source of truth. That way even if/when we make DB changes the dashboard queries will still work. Specifically for things like getting free balances, app instances, etc. Since the CF node functions essentially just read the DB directly it's easier this way. Obviously some cases will be better suited for direct SQL queries.

**Comment by hthillman** [comment]
Got it -- I thought you were saying to call CF functions directly from the frontend.

**Comment by ArjunBhuptani** [comment]
Stale - closing for now and we can open new issues for specific dashboard tasks as they come up.
