### ISSUE TITLE
[test-runner] Dropped message or client is offline tests

### ISSUE THREAD

**Issue by ArjunBhuptani** [ConnextProject/indra#714]
## Deposit tests
- [x] Bot A proposes deposit, but node doesn't receive the NATS message
- [x] Bot A proposes deposit, but node only receives the NATS message after timeout is over
- [x] Bot A proposes deposit, but node doesn't respond
- [x] Bot A proposes deposit, but node only responds after timeout is over
- [x] Bot A goes offline after proposing deposit and then comes back after timeout is over
- [x] Bot A proposes deposit, but then deletes their store

## Swap tests
- [x] Bot A tries to install swap but there’s no response from node
- [x] Bot A installs swap app successfully but then goes offline for uninstall
- [x] Bot A install swap app successfully but then node goes offline for uninstall
- [x] Bot A installs swap app successfully but then deletes store (before uninstall)

## Async Transfer tests
- [x] Bot A successfully installs transfer, goes offline before sending paymentId/preimage, then comes online and has the pending installed transfer
- [x] Bot A successfully installs transfer, goes offline before sending paymentId/preimage, and stays offline? (// is this the same as above?)
- [x] Bot A installs transfer successfully, bot B proposes install but node is offline
- [x] Bot A installs transfer successfully, bot B installs successfully, but node is offline
- [x] Bot A installs transfer successfully, bot B install succesfully, takesAction, then goes offline
- [x] Bot A installs, bot B installs, takesAction, then uninstalls. Node tries to take action with Bot A but Bot A is offline but then comes online later (node needs to know bot A is back online and clean up pending transfers)
- [x] Bot A installs, bot B installs, takesAction, then uninstalls. Node takes action, then uninstalls with Bot A but Bot A goes offline during uninstall and comes back on later

## Withdraw tests
- [x] Bot A proposes withdrawal but doesn't receive a response from node
- [x] Bot A proposes withdrawal and then goes offline before node responds
- [x] Bot A proposes a node submitted withdrawal but node is offline for one message (commitment should be written to store and retried)

**Comment by bohendo** [comment]
I don't think it's useful to enumerate all the tests we want here. The time spent doing this would be better spend adding these stubs directly to the test suite eg 

```
test("Bot A proposes a node submitted withdrawal but node is offline for one message (commitment should be written to store and retried)", async () => {})
```

**Comment by LayneHaber** [comment]
IMO helps to group it by the blocker, plus this obviously will be done in separate PRs. Just helps to keep an eye on things (though this issue should really be a tracker with the number of tests in here).

Note: tests are blocked by #713

**Comment by LayneHaber** [comment]
Added tracker label and broke into issues:
- deposit #755 
- swap #756 
- transfer #757 
- withdraw #758
