### ISSUE TITLE
[tracker] Collateral Management Service

### ISSUE THREAD

**Issue by LayneHaber** [ConnextProject/indra#802]
Things needed for 3rd party collateral management services.

- [ ] #788 Scaffolding including a django app that has the following API endpoints 
```
1. getTargets(hashOfXpub: string) => 
{ 
  collateralize: [
    <ASSET_ID>: {
      upperBound, // collateralize up to this
      lowerBound // when this hits, collateralize, then re-request bounds
    }[]
  ],
  reclaim: [
   <ASSET_ID>: {
      upperBound, // when this hits, reclaim, re-request bounds
      lowerBound // leave this much in the channel
    }[]
  ]
}

2. getDisputes() => string[]
```
- [ ] #791 Node endpoint to pull data to the API
- [ ] #792 Make sure deposit/withdrawals/etc. are tracked in `onchain_transactions`
- [ ] #793 Node should create a view for the service with anonymized transaction/payment data
- [ ] #794 Replace all `requestCollateral` calls in node to request from service + update logic (including fallback logic)
- [ ] #795 Remove `requestCollateral` from client API
- [ ] #796 Service should have its own database that it can query + update from node data (have `onchain_transactions` and `transfers` views)
- [ ] #797 Token/simple bearer auth for service (also generate API Keys for clients)
- [ ] #798 Remove `paymentProfiles` from node
- [ ] #799 Make sure node can handle unusually large payments (outside of `targets` returned from service)
- [ ] #800 Node endpoint to get list of all xpubs it should dispute + set up nightly tasks
- [ ] #801 Deployment and CD/CI of collateral management service
